import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {fetchRetailSales} from './counterAPI';

const initialState = {
  data: null,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchRetailSales(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchRetailSalesAsync = createAsyncThunk(
  'sales/fetchRetailSales',
  async () => {
    const {data} = await fetchRetailSales();
    // The value we return becomes the `fulfilled` action payload
    return data;
  }
);

export const retailSalesSlice = createSlice({
  name: 'retailSales',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchRetailSalesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchRetailSalesAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value = action.payload;
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectRetailSales = state => state.counter.value;

export default retailSalesSlice.reducer;
